---

# Which user get which ssh key:
users:
  l3d:
   - l3d@backup.l3d.yt
   - l3d@derpy.l3d.yt
   - l3d@mobile.l3d.yt
   - l3d@pinkie.l3d.yt
   - l3d@business.wingcon.com
  alex:
   - alex@toolbox

# admins on local device:
admins:
  - l3d
  - alex
# users createt on this host
accounts:
  - l3d
  - alex

ssh_public_key_store: 'admin_ssh_keys'
home_sweet_home: false
only_allow_ed25519: false

# copy some motion config
copy_these_files:
 - { src: 'files/motion/{{ ansible_hostname }}-motion.cfg', dest: "/usr/local/etc/motion/motion.cfg" }
 - { src: 'files/motion/cam01.cfg', dest: "/usr/local/etc/motion/cam01.cfg" }
 - { src: 'files/motion/cam02.cfg', dest: "/usr/local/etc/motion/cam02.cfg" }
 - { src: 'files/motion/cam03.cfg', dest: "/usr/local/etc/motion/cam03.cfg" }
 - { src: 'files/motion/cam04.cfg', dest: "/usr/local/etc/motion/cam04.cfg" }
 - { src: 'files/motion/cam05.cfg', dest: "/usr/local/etc/motion/cam05.cfg" }
 - { src: 'files/motion/cam06.cfg', dest: "/usr/local/etc/motion/cam06.cfg" }
 - { src: 'files/motion/cam07.cfg', dest: "/usr/local/etc/motion/cam07.cfg" }
 - { src: 'files/motion/cam08.cfg', dest: "/usr/local/etc/motion/cam08.cfg" }
 - { src: 'files/motion/cam09.cfg', dest: "/usr/local/etc/motion/cam09.cfg" }
 - { src: 'files/motion/cam0a.cfg', dest: "/usr/local/etc/motion/cam0a.cfg" }
 - { src: 'files/motion/cam0b.cfg', dest: "/usr/local/etc/motion/cam0c.cfg" }
 - { src: 'files/motion/cam0c.cfg', dest: "/usr/local/etc/motion/cam0b.cfg" }
 - { src: 'files/motion/cam0d.cfg', dest: "/usr/local/etc/motion/cam0d.cfg" }
