---
# Which user get which ssh key:
users:
  l3d:
   - l3d@derpy.l3d.yt
   - l3d@backup.l3d.yt
   - l3d@mobile.l3d.yt
   - l3d@pinkie.l3d.yt
   - l3d@business.wingcon.com
  alex:
   - alex@toolbox
  matt:
   - matt@mknoll@Matthiass-MacBook-Pro.local

# people with sudo permissions at the ansible hosts:
admins:
  - l3d
  - alex
  - matt

# users createt at the ansible hosts:
accounts:
  - l3d
  - alex
  - matt

# where are ssh keys located?
ssh_public_key_store: 'admin_ssh_keys'

# do not configure .bashrc multiple times
home_sweet_home: false

# we only accept post-quantum cryptographic keys
only_allow_ed25519: true
