---
- name: Apply common configuration of all Switches
  hosts: switche
  tags: cisco
  tasks:
    - name: print ssh password
      debug:
        msg: "User: {{ ansible_user }} \n Password: {{ ansible_ssh_pass }} \nPrivg: {{ ansible_become_pass }}"

