---

- name: secure access to toolbox gateway
  hosts: router
  tags:
  - access
  - ssh
  - auth
  roles:
   - ssh-auth
   - sshd
  vars:
    - ansible_ssh_user: 'root'

- name: install some fancy packages
  hosts: router
  tags:
  - setup
  - base
  roles:
   - base-packages
  vars: 
    - ansible_ssh_user: 'root'

- name: create a fancy feature complete home
  hosts: router
  tags:
  - setup
  - base
  - home
  roles:
   - dotfiles
   - install-bat

- name: configure the basic network
  hosts: router
  tags:
  - setup
  - network
  - ip
  roles:
   - networking
   - resolver
   - sysctl



