---

- name: secure access to toolbox gateway
  hosts: router
  tags:
  - access
  - ssh
  - auth
  roles:
   - ssh-auth
   - sshd
  vars:
    - ansible_ssh_user: 'root'

- name: create a fancy feature complete home
  hosts: router
  tags:
  - setup
  - base
  roles:
   - base-packages
   - dotfiles
   - install-bat


