---
#- name: Setup Raspberry Pi to speak with ansible
#  gather_facts: False
#  become: true
#  tags:
#  - always
#  - raspberry
#  - setup
#  roles:
#    - pi-setup

- name: secure access to toolbox gateway
  hosts: kubernetes
  tags:
  - access
  - ssh
  - auth
  - newuser
  roles:
   - ssh-auth
   - sshd
  vars:
    - ansible_ssh_user: 'ansible'

- name: install some fancy packages
  hosts: kubernetes
  tags:
  - setup
  - base
  roles:
   - base-packages

- name: create a fancy feature complete home
  hosts: kubernetes
  tags:
  - setup
  - base
  - home
  - newuser
  roles:
   - dotfiles

- name: create cubernetes
  become: true
  hosts: kubernetes
  tags:
   - setup
   - docker
   - kubernetes
  roles:
    - docker
    - kubernetes
