---
- hosts: openstack
  tags: default
  pre_tasks:
    - name: check if ansible is up to date.
      assert:
        that: "ansible_version.full is version_compare('2.8', '>=')"
        msg: >
          "You must update Ansible to at least 2.8 to use this version of the toolbox openstack playbook."

#- name: Setup Raspberry Pi to speak with ansible
#  gather_facts: False
#  become: true
#  tags:
#  - always
#  - raspberry
#  - setup
#  roles:
#    - pi-setup

- name: secure access to toolbox gateway
  hosts: kubernetes
  tags:
  - access
  - ssh
  - auth
  - newuser
  roles:
   - ssh-auth
   - sshd
  vars:
    - ansible_ssh_user: 'ansible'

- name: install some fancy packages
  hosts: kubernetes
  tags:
  - setup
  - base
  roles:
   - base-packages

- name: create a fancy feature complete home
  hosts: kubernetes
  tags:
  - setup
  - base
  - home
  - newuser
  roles:
   - dotfiles

- name: create cubernetes
  become: true
  hosts: kubernetes
  tags:
   - setup
   - docker
   - kubernetes
  roles:
    - docker
    - kubernetes
