---
- hosts: openstack
  tags: default
  pre_tasks:
    - name: check if ansible is up to date.
      assert:
        that: "ansible_version.full is version_compare('2.8', '>=')"
        msg: >
          "You must update Ansible to at least 2.8 to use this version of the toolbox openstack playbook."

- name: secure access to toolbox openstack cluster
  hosts: openstack
  tags:
  - access
  - ssh
  - auth
  - newuser
  - ssh-auth
  - sshd
  roles:
   - manage_users
   - ssh-auth
   - sshd
  vars:
    - ansible_ssh_user: 'ansible'

- name: install some fancy packages
  hosts: openstack
  tags:
  - setup
  - base
  - packages
  - base-packages 
  roles:
   - base-packages

- name: create a fancy feature complete home
  hosts: openstack
  tags:
  - setup
  - base
  - home
  - newuser
  - dotfiles
  - install-bat
  roles:
   - dotfiles
   - install-bat


