---
#- name: Setup Raspberry Pi to speak with ansible
#  gather_facts: False
#  become: true
#  tags:
#  - always
#  - raspberry
#  - setup
#  roles:
#    - pi-setup

- name: secure access to toolbox gateway
  hosts: strichliste
  tags:
  - access
  - ssh
  - auth
  - newuser
  roles:
   - ssh-auth
   - sshd
  vars:
    - ansible_ssh_user: 'ansible'

- name: install some fancy packages
  hosts: strichliste
  tags:
  - setup
  - base
  roles:
   - base-packages
  gather_facts: false

- name: create a fancy feature complete home
  hosts: strichliste
  tags:
  - setup
  - base
  - home
  - newuser
  roles:
   - dotfiles
  gather_facts: false

- name: create a fancy feature complete home
  hosts: strichliste
  tags:
  - ugly
  - sh1t
  - docker
  - docker-pi
  roles:
   - docker-pi
  gather_facts: true




