---
#- name: Setup Raspberry Pi to speak with ansible
#  gather_facts: False
#  tags:
#  - always
#  - raspberry
#  - setup
#  roles:
#    - pi-setup

- name: secure access to toolbox gateway
  hosts: strichliste
  tags:
  - access
  - ssh
  - auth
  - newuser
  roles:
   - ssh-auth
   - sshd
  vars:
    - ansible_ssh_user: 'ansible'

- name: install some fancy packages
  hosts: strichliste
  tags:
  - setup
  - base
  roles:
   - base-packages
  gather_facts: false

- name: create a fancy feature complete home
  hosts: strichliste
  tags:
  - setup
  - base
  - home
  - newuser
  roles:
   - dotfiles
  gather_facts: false

- name: strichliste-docker
  hosts: strichliste
  tags:
  - strichliste-docker
  - docker-pi
  - strichliste
  roles:
   - strichliste-docker
  gather_facts: true


