---

- name: Install isc-dhcp-server
  become: yes
  apt:
    name: 'isc-dhcp-server'
    state: 'latest'
    update_cache: yes
    cache_valid_time: 86400

- name: Copy ISC DHCP Gateway config (backup)
  become: yes
  template:
    src: 'templates/isc-dhcp-server.conf'
    dest: '/etc/default/isc-dhcp-server'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Debug
  debug:  
    var: leases

- name: Copy ISC DHCP config for this specific gateway
  become: yes
  template:
    src: 'templates/dhcpd.conf'
    dest: '/etc/dhcp/dhcpd.conf'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify:
    - restart dhcpcd

