---
- name: install strichliste requirements
  become: yes
  package:
    name:
      - lsb-release
      - apt-transport-https
      - ca-certificates
    state: present

- name: get php sources gpg signature
  become: yes
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg

- name: add php repo
  become: yes
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"  
    state: present

- name: install php7.3
  become: true
  apt:
    name: 
      - php7.3
      - git 
      - curl  
      - unzip
      - sqlite3
      - php7.3-cli 
      - php7.3-xml
      - php7.3-zip
      - php7.3-sqlite3
      - nginx
      - php7.3-fpm
    state: present

- name: copy nginx vhost config
  become: yes
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/sites-enabled/strichliste-backend
    owner: root
    mode: 0644
