---

- name: restart dhcpcd
  become: yes
  service:
    name: isc-dhcp-server
    state: restarted

- name: dpkg reconfigure isc-dhcp-server
  command: 'dpkg-reconfigure -f noninteractive isc-dhcp-server'

