---
hostname: cheerilee.tbbs.me

management: true
management_access: 172.23.31.254 
management_interface: Vlan1

interface:
  default:
    name: "Default Interface"
    vlan: 0
  GigabitEthernet0/1:
    name: "Toolbox Uplink"
    vlan: 0
  GigabitEthernet0/6:
    name: "VOC Uplink - Dose ruum42 -> beamer"
    vlan: 0
  GigabitEthernet0/7:
    name: "Freifunk Input"
    vlan: 7
  GigabitEthernet0/17:
    name: "AP ruum42"
    vlan: 't'
  GigabitEthernet0/26:
    name: "Switch ruum42 - Dose ruum43 -> fenster"
    vlan: 0
  GigabitEthernet0/27:
    name: "Freifunk output"
    vlan: 7
  GigabitEthernet0/42:
    name: "Uplink E-werkstatt - AP - dose22"
    vlan: 't'
  GigabitEthernet0/43:
    name: "Uplink AP bibliothek - dose19 - rechts"
    vlan: 't'
  GigabitEthernet0/44:
    name: "besprechungsraum fenster - dose 3"
    vlan: '7'
  GigabitEthernet0/45:
    name: "Uplink Switch Fraesenraum"
    vlan: 0
  GigabitEthernet0/46:
    name: "Uplink Keller + keller AP"
    vlan: 't'
